[package]
name = "howmanysmall/roact-hooked-luau"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A port of littensy's roact-hooked package with a few changes for my code style."
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dependencies]
Roact = "roblox/roact@1.4.4"
ThreadUtilities = "howmanysmall/thread-utilities@1.0.1"
